# Generated by Django 5.2.5 on 2025-10-16 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_contenidosolicitud_declaracion_originalidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='visto_bueno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='visto_bueno_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='visto_bueno_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
    ]
