# Generated by Django 5.2.5 on 2025-10-16 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_seguimiento_visto_bueno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='visto_bueno',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='visto_bueno_fecha',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='visto_bueno_por',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='visto_bueno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='visto_bueno_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='visto_bueno_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visto_bueno_solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
